# This is a basic workflow to help you get started with Actions

name: 01 Building Blocks

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  echo-hello:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Say Hello
        run: echo Hello, world!
        
  echo-goodbye:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Runs a set of commands using the runners shell
      # - name: Failed step
      #   run: |
      #        echo "I will fail"
      #        exit 1
      - name: Successful step
        run: |
             echo "I will succeed"
             exit 0
      - name: Say goodbye
        run: echo "Goodbye"
