name: 06 Contexts
run-name: My Custom Workflow Run Name - ${{runner.os}}

on:
    push:
      
    workflow_dispatch: 
  
jobs:
  echo-data:
    runs-on: ubuntu-latest

    steps:
      - name: Display Information
        run: |
            echo "Event name: ${{github.event_name}}"
            echo "Event Ref: ${{github.ref}}"
            echo "Event Sha: ${{github.sha}}"
            echo "Event Actor: ${{github.actor}}"
            echo "Event Workflow: ${{github.workflow}}"
            echo "Event RunID: ${{github.run_id}}"
            echo "Event RunNumber: ${{github.run_number}}"
             
      - name: Retrieve Variable
        run: |
            echo "Variable value: ${{vars.MY_VAR}}"