name: 06 Contexts
run-name: 06 Contexts | DEBUG - ${{inputs.debug}}

on:
    # push:
      
    workflow_dispatch: 
      inputs:
        debug:
          type: boolean
          default: false
env:
  MY_WORKFLOW_VAR: "workflow"
  MY_OVERWRITTEN_VAR: "workflow"

jobs:
  echo-data:
    runs-on: ubuntu-latest
    env:
      MY_JOB_VAR: "job"
      MY_OVERWRITTEN_VAR: "job"

    steps:
      - name: Display Information
        run: |
            echo "Event name: ${{github.event_name}}"
            echo "Event Ref: ${{github.ref}}"
            echo "Event Sha: ${{github.sha}}"
            echo "Event Actor: ${{github.actor}}"
            echo "Event Workflow: ${{github.workflow}}"
            echo "Event RunID: ${{github.run_id}}"
            echo "Event RunNumber: ${{github.run_number}}"
             
      - name: Retrieve Variable
        run: |
            echo "Variable value: ${{vars.MY_VAR}}"
            
      - name: Print Env Variables
        env:
          MY_OVERWRITTEN_VAR: "step"
        run: |
            echo "MY_WORKFLOW_VAR value: ${{env.MY_WORKFLOW_VAR}}"
            echo "MY_JOB_VAR value: ${{env.MY_JOB_VAR}}"
            echo "MY_OVERWRITTEN_VAR value: ${{env.MY_OVERWRITTEN_VAR}}"
      - name: Print Env Variables Again
        run: |
            echo "MY_WORKFLOW_VAR value: ${{env.MY_WORKFLOW_VAR}}"
            echo "MY_JOB_VAR value: ${{env.MY_JOB_VAR}}"
            echo "MY_OVERWRITTEN_VAR value: ${{env.MY_OVERWRITTEN_VAR}}"
  
  echo-data-again:
    runs-on: ubuntu-latest
    steps:
      - name: Print Env Variables
        run: |
            echo "MY_WORKFLOW_VAR value: $MY_WORKFLOW_VAR"
            echo "MY_OVERWRITTEN_VAR value: $MY_OVERWRITTEN_VAR"