name: 07 Expressions
run-name: 07 Expressions | DEBUG - ${{inputs.debug && 'ON' || 'OFF'}}

env:
  MY_WORKFLOW_VAR: ${{vars.MY_VAR || 'default'}}

on:
    # push:
      
    workflow_dispatch:
      inputs:
        debug:
          type: boolean
          default: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: '[debug] Pring startup data'
        if: ${{inputs.debug}}
        run: |
          echo "Triggered by: ${{github.event_name}}"
          echo "Branch: ${{github.ref}}"
          echo "Commit Sha: ${{github.sha}}"
          echo "Ronner OS: ${{runner.os}}"
      - name: "[debug] Whan triggered from main"
        if: "${{inputs.debug && github.ref == 'refs/heads/main'}}"
        run: |
          echo "I am triggered from main"
      - name: Greeting
        run: echo 'Hello, world'