name: 11 Inputs
run-name: 11 Inputs | DEBUG - ${{inputs.debug && 'ON' || 'OFF'}}

on:

    workflow_dispatch:
        
      inputs:
        dry-run:
          type: boolean
          description: Skip deployment and only print build output
          default: false
        target:
          type: environment
          required: true
          description: Which environment theworkflow will target
        debug:
          type: boolean
          default: false
        tag:
          type: choice
          options:
            - v1
            - v2
            - v3
          default: v3
          description: Release from which to build and deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Builld
        run: |
          echo "Building from tag ${{inputs.tag}}"
  deploy:
    runs-on: ubuntu-latest
    if: ${{!inputs.dry-run}}
    environment: ${{inputs.target}}
    steps:
      - name: Deploy
        run: |
          echo "Deploying to ${{inputs.target}}"