name: 12 Outputs
run-name: 12 Outputs | DEBUG - ${{inputs.debug && 'ON' || 'OFF'}}

on:

    workflow_dispatch:
        
      inputs:

        build-status:
          type: choice
          options:
            - success
            - failure
          default: success
 
        debug:
          type: boolean
          default: false

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{steps.build.outputs.status}}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo "$GITHUB_OUTPUT"
      - name: Build
        id: build
        run: |
          echo "status=success" >> "$GITHUB_OUTPUT"
  
  build2:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{steps.build2.outputs.status}}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo "$GITHUB_OUTPUT"
      - name: Build
        id: build2
        run: |
          echo "status=${{inputs.build-status}}" >> "$GITHUB_OUTPUT"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: 
      - build
      
    if: ${{needs.build.outputs.build-status == 'success'}}
    steps:
      - name: Deploy
        run: echo "Deploying"


  deploy-prod2:
    runs-on: ubuntu-latest
    needs: 
      - build2
      
    if: ${{needs.build2.outputs.build-status == 'success'}}
    steps:
      - name: Deploy
        run: echo "Deploying"
