name: 14 Artifacts
run-name: 14 Artifacts | DEBUG - ${{inputs.debug && 'ON' || 'OFF'}}

on:
      
    workflow_dispatch:
      inputs:
        debug:
          type: boolean
          default: false
env:
  build-artifact-key: app-${{github.sha}}
  test-coverage-key: test-coverage-${{github.sha}}
jobs:
  test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 14-artifacts/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - name: Download Cached Dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: 14-artifacts/react-app/node_modules
          key: deps-node-modules-${{hashFiles('14-artifacts/react-app/package-lock.json')}}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Unit Tests
        run: npm run test -- --coverage
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.test-coverage-key}}
          path: 14-artifacts/react-app/coverage
      - name: Build code
        run: npm run build
      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.artifact-key}}
          path: 14-artifacts/react-app/build

  deploy:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - name: Download buid artifact
        uses: actions/download-artifact@v7
        with:
          name: ${{env.artifact-key}}
          path: build
      - name: Show folder structure
        run: ls -R